export const FALLBACK_VENDOR_CATEGORY_MAP = {
  'Generic Medicine': [
    'Addiction',
    'Anxiety & Depression',
    'Sleeplessness',
    'Weak Memory',
    'Acne & Pimples',
    'Dark Circles & Marks',
    'Wrinkles & Aging',
    'Hair Fall',
    'Dandruff',
    'Asthma',
    'Bronchitis',
    'Cough',
    'Indigestion/Acidity/Gas',
    'Diabetes',
    'Blood Pressure',
    'Headache & Migraine',
    'Back & Knee Pain',
    'Arthritis & Joint Pains',
    'Sun Pharma',
    'Cipla',
    'Lupin',
    'Pfizer',
    'Abbott',
    'Tablets & Capsules',
    'Syrups & Suspensions',
    'Creams & Ointments',
  ],
  'Ayurveda Medicine': ['Medicines', 'Single Remedies', 'Herbal Food & Juices'],
  Homeopathy: [
    'Medicines',
    'Cosmetics',
    'Dilutions',
    'Mother Tinctures',
    'Biochemic',
    'Bach Flower',
    'Homeopathy Kits',
    'Triturations',
    'Millesimal LM Potency',
    'Bio Combination',
  ],
  'Lab Tests': ['General', 'Diabetes', 'Cardiac', 'Thyroid', 'Liver', 'Kidney', 'Vitamins', 'Infection', 'Women'],
  Disease: [
    'Addiction',
    'Anxiety & Depression',
    'Sleeplessness',
    'Weak Memory',
    'Acne & Pimples',
    'Dark Circles & Marks',
    'Wrinkles & Aging',
    'Hair Fall',
    'Dandruff',
    'Asthma',
    'Bronchitis',
    'Cough',
    'Indigestion/Acidity/Gas',
    'Diabetes',
    'Blood Pressure',
    'Headache & Migraine',
    'Back & Knee Pain',
    'Arthritis & Joint Pains',
  ],
  Nutrition: ['Sports Nutrition', 'Health Food & Drinks', 'Vitamin & Dietary Supplements', 'Green Teas', 'Digestives'],
  'Organic Products': ['Organic Foods', 'Coffee & Tea', 'Ghee', 'Atta/Flour'],
  'Personal Care': ['Aroma Oils', 'Mens Grooming', 'Female Care', 'Skin Care', 'Bath & Shower', 'Hair Care', 'Elderly Care', 'Mosquito Repellents', 'Oral Care'],
  Fitness: ['Supports & Splints', 'Health Devices', 'Fitness Equipment', 'Hospital Supplies', 'Aroma Therapy', 'Disability Aids', 'Massagers', 'Bandages & Tapes', 'Walking Sticks'],
  'Sexual Wellness': ['Supplements', 'Condoms'],
  Consultation: ['Homeo Treatment', 'Ayurveda Treatment', 'Unani Treatment', 'Diet Counselling'],
  Unani: ['Unani Medicines', 'Habbe & Qurs', 'Majun & Jawarish', 'Safoof, Labub & Kushta', 'Sharbat, Sirka & Arq', 'Lauq & Saoot', 'Khamira & Itrifal', 'Roghan & Oils', 'Unani Brands'],
  'Baby Care': ['Tonics & Supplements', 'Bath & Skin', 'Wipes & Diapers', 'Gift Packs'],
} as const;

export const FALLBACK_SUBCATEGORY_MAP_BY_TYPE = {
  Homeopathy: {
    Medicines: ['SBL', 'Dr. Reckeweg (Germany)', 'Willmar Schwabe (Germany)', 'BJain'],
    Cosmetics: ['Hair Care', 'Skin Care', 'Oral Care'],
    Dilutions: ['3 CH', '6 CH', '12 CH', '30 CH', '200 CH', '1000 CH'],
    'Mother Tinctures': ['SBL', 'Dr. Reckeweg (Germany)', 'Willmar Schwabe India', 'BJain'],
    Biochemic: ['SBL', 'Dr. Reckeweg (Germany)', 'BJain', 'Willmar Schwabe India'],
    'Bach Flower': ['Bach Flower Remedies', 'Bach Flower Kits'],
    'Homeopathy Kits': ['Homeopathy Kits'],
    Triturations: ['SBL', 'Dr. Reckeweg (Germany)', 'Willmar Schwabe India', 'BJain'],
    'Millesimal LM Potency': ['SBL', 'BJain'],
    'Bio Combination': ['SBL', 'Dr. Reckeweg (Germany)', 'BJain', 'Willmar Schwabe India', 'Haslab (HSL)'],
  },
  'Ayurveda Medicine': {
    Medicines: ['Himalaya', 'Organic India', 'Baidyanath', 'Dabur', 'Zandu', 'Charak', 'Aimil'],
    'Single Remedies': ['Ras & Sindoor', 'Bhasm & Pishti', 'Vati & Gutika & Guggulu', 'Asava Arishta & Kadha', 'Loha & Mandur', 'Churan & Powder & Avleha & Pak', 'Tailam & Ghrita'],
    'Herbal Food & Juices': ['Chyawanprash', 'Honey', 'Digestives', 'Herbal & Vegetable Juice'],
  },
  Nutrition: {
    'Sports Nutrition': ['Proteins', 'Fat Burner', 'Weight Gainers', 'Pre Post Workout', 'Aminos', 'Creatines'],
    'Health Food & Drinks': ['Spreads & Sugar & Honey', 'Oils', 'Herbal & Vegetable Juices', 'Health Drinks', 'Healthy Snacks & Bars'],
    'Vitamin & Dietary Supplements': ['Vitamin & Dietary Supplements'],
    'Green Teas': ['Green Teas'],
    Digestives: ['Digestives'],
  },
  'Organic Products': {
    'Organic Foods': ['Organic Foods'],
    'Coffee & Tea': ['Coffee & Tea'],
    Ghee: ['Ghee'],
    'Atta/Flour': ['Atta/Flour'],
  },
  'Personal Care': {
    'Aroma Oils': ['Essential Oils'],
    'Mens Grooming': ['Beard Oils and Wax', 'Shaving Cream & Gels', 'Men Wellness'],
    'Female Care': ['Intimate Care', 'Pregnancy & Maternity Care'],
    'Skin Care': ['Face', 'Body', 'Foot Care', 'Sanitizers & Hand Wash'],
    'Bath & Shower': ['Shower Gel & Hand Wash', 'Soaps', 'Talcs & Deos'],
    'Hair Care': ['Shampoo & Conditioners', 'Hair Oils & Creams', 'Hair Serum & Mask', 'Hair Color & Dyes', 'Henna Mehandi'],
    'Elderly Care': ['Elderly Care'],
    'Mosquito Repellents': ['Mosquito Repellents'],
    'Oral Care': ['Toothpaste', 'Gums Care'],
  },
  'Baby Care': {
    'Tonics & Supplements': ['Tonics & Supplements'],
    'Bath & Skin': ['Shampoos & Bath Gels', 'Baby Oils', 'Baby Powder', 'Soaps'],
    'Wipes & Diapers': ['Wipes & Diapers'],
    'Gift Packs': ['Gift Packs'],
  },
  Fitness: {
    'Supports & Splints': ['Shoulder Support', 'Elbow Support', 'Back Support', 'Knee Support', 'Ankle Support'],
    'Health Devices': ['Weighing Scales', 'BP Monitors', 'Thermometer', 'Respiratory Care'],
    'Fitness Equipment': ['Exercisers', 'Weights'],
    'Hospital Supplies': ['Stethoscopes', 'Protective Gears', 'Hospital Beds'],
    'Aroma Therapy': ['Aroma Therapy'],
    'Disability Aids': ['Disability Aids'],
    Massagers: ['Massagers'],
    'Bandages & Tapes': ['Bandages & Tapes'],
    'Walking Sticks': ['Walking Sticks'],
  },
  Unani: {
    'Unani Medicines': ['Unani Medicines'],
    'Habbe & Qurs': ['Habbe & Qurs'],
    'Majun & Jawarish': ['Majun & Jawarish'],
    'Safoof, Labub & Kushta': ['Safoof, Labub & Kushta'],
    'Sharbat, Sirka & Arq': ['Sharbat, Sirka & Arq'],
    'Lauq & Saoot': ['Lauq & Saoot'],
    'Khamira & Itrifal': ['Khamira & Itrifal'],
    'Roghan & Oils': ['Roghan & Oils'],
    'Unani Brands': ['Hamdard', 'New Shama', 'Dehlvi', 'Rex'],
  },
} as const;

export const FALLBACK_DISEASE_SUBCATEGORY_MAP = {
  Mind: ['Addiction', 'Anxiety & Depression', 'Sleeplessness', 'Weak Memory'],
  Face: ['Acne & Pimples', 'Dark Circles & Marks', 'Wrinkles & Aging'],
  Hair: ['Hair Fall', 'Dandruff', 'Alopecia & Bald Patches', 'Premature Graying', 'Lice'],
  'Eyes & Ear': ['Conjunctivitis', 'Cataract', 'Eye Strain', 'Glaucoma', 'Styes', 'Ear Pain', 'Ear Wax'],
  'Nose & Throat': ['Allergic Rhinitis', 'Sneezing & Running Nose', 'Sinusitis & Blocked Nose', 'Snoring', 'Tonsilitis & Throat Pain', 'Laryngitis & Hoarse Voice'],
  'Nervous System': ['Headache & Migraine', 'Vertigo/Motion Sickness', 'Neuralgia & Nerve Pain', 'Epilepsy & Fits'],
  'Mouth, Gums & Teeth': ['Bad Breath', 'Bleeding Gum/Pyorrhoea', 'Mouth Ulcers/Aphthae', 'Cavities & Tooth Pain', 'Stammering'],
  Respiratory: ['Asthma', 'Bronchitis', 'Cough', 'Pneumonia'],
  'Rectum & Piles': ['Constipation', 'Piles & Fissures', 'Loose Motions/Diarrhoea', 'IBS & Colitis', 'Fistula', 'Worms'],
  'Digestive System': ['Indigestion/Acidity/Gas', 'Loss of Appetite', 'Jaundice & Fatty Liver', 'Stomach Pain & Colic', 'Vomiting & Nausea', 'Gall Stones', 'Appendicitis', 'Hernia'],
  'Heart & Cardiovascular': ['Heart Tonics', 'Chest Pain & Angina', 'Cholesterol & Triglyceride'],
  'Urinary System': ['Urinary Tract Infection', 'Kidney Stone', 'Frequent Urination'],
  'Bone, Joint & Muscles': ['Arthritis & Joint Pains', 'Back & Knee Pain', 'Cervical Spondolyisis', 'Injuries & Fractures', 'Gout & Uric Acid', 'Osteoporosis', 'Sciatica', 'Heel Pain'],
  'Skin & Nails': ['Bed Sores', 'Boils & Abscesses', 'Burns', 'Cyst & Tumor', 'Eczema', 'Herpes', 'Nail Fungus', 'Psoriasis & Dry Skin', 'Rash/Itch/Urticaria/Hives', 'Vitiligo & Leucoderma', 'Warts & Corns'],
  'Fevers & Flu': ['Dengue', 'Flu & Fever', 'Malaria', 'Typhoid'],
  'Male Problems': ['Hydrocele', 'Premature Ejaculation', 'Impotency', 'Prostate Enlargement'],
  'Female Problems': ['Underdeveloped Breasts', 'Enlarged Breasts', 'Leucorrhoea', 'Excessive Menses', 'Vaginitis', 'Menopause', 'Painful, Delayed & Scanty Menses'],
  'Old Age Problems': ['Parkinsons & Trembling', 'Involuntary Urination', 'Alzheimers'],
  'Children Problems': ['Low Height', 'Autism', 'Bed Wetting', 'Immunity', 'Teething Troubles', 'Irritability & Hyperactive'],
  'Lifestyle Diseases': ['Diabetes', 'Blood Pressure', 'Obesity', 'Thyroid', 'Hang Over', 'Varicose Veins'],
  Tonics: ['Anaemia', 'Blood Purifiers', 'General Tonics', 'Weakness & Fatigue'],
} as const;

export const FALLBACK_LAB_CATEGORIES = FALLBACK_VENDOR_CATEGORY_MAP['Lab Tests'];
